apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mysql.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "mysql.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "mysql.fullname" . }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: {{ include "mysql.fullname" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: MYSQL_DATABASE
          value: assignment
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-creds
              key: username
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-creds
              key: password
        args: ["--default-authentication-plugin=mysql_native_password"]
        ports:
        - containerPort: {{ .Values.service.port }}
          name: {{ include "mysql.fullname" . }}-port
        volumeMounts:
          - name: {{ .Values.volume.name }}
            mountPath: {{ .Values.volume.mountPath }}
      volumes:
      - name: {{ .Values.volume.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistentVolume.claimName }}
