apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    {{- include "mysql.selectorLabels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistentVolume.storageClassName }}
  capacity:
    storage: {{ .Values.persistentVolume.storage }}
  accessModes:
    - {{ .Values.persistentVolume.accessMode }}
  hostPath:
    path: {{ .Values.persistentVolume.hostPath }}
