apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistentVolume.claimName }}
  labels:
    {{- include "mysql.selectorLabels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistentVolume.storageClassName }}
  accessModes:
    - {{ .Values.persistentVolume.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistentVolume.storage }}
