apiVersion: v1
kind: Service
metadata:
  name: {{ include "webserver.fullname" . }}
  labels:
    {{- include "webserver.selectorLabels" . | nindent 4 }}
spec:
  #type: LoadBalancer
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
  selector:
    {{- include "webserver.selectorLabels" . | nindent 4 }}
